version: '2.2'

services:
 mssql:
  image: sitecorecommercedocker_mssql
  mem_limit: 2048m
  cpu_count: 4
  networks:
    app_net:
      ipv4_address: 172.16.3.3 
  environment:
    ACCEPT_EULA: "Y"
    sa_password: "my_Sup3rSecret!!"

 solr:
  image: sitecorecommercedocker_solr
  mem_limit: 4096m
  networks:
    app_net:  
      ipv4_address: 172.16.3.5

 xconnect:
  image: sitecorecommercedocker_xconnect
  volumes:
    - .\logs\xconnect:C:\inetpub\wwwroot\xconnect\App_data\Logs
  networks:
    app_net:
      ipv4_address: 172.16.3.6  
  depends_on:
    - mssql
    - solr

 sitecore:
  image: sitecorecommercedocker_sitecore
  cpu_count: 6
  volumes:
    - .\logs\sitecore:c:\inetpub\wwwroot\sitecore\App_Data\logs
    - .\build\website:C:\Workspace
    - .:c:\vagrant
  depends_on:
    - xconnect
    - mssql
    - solr
  networks:
    app_net:
      ipv4_address: 172.16.3.4   

 commerce:
  build: ./Docker/commerce
  cpu_count: 4
  volumes:
    - .\logs\commerce\CommerceAuthoring_Sc9:C:\inetpub\wwwroot\CommerceAuthoring_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceMinions_Sc9:C:\inetpub\wwwroot\CommerceMinions_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceOps_Sc9:C:\inetpub\wwwroot\CommerceOps_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceShops_Sc9:C:\inetpub\wwwroot\CommerceShops_Sc9\wwwroot\logs
    - .\logs\commerce\SitecoreIdentityServer:C:\inetpub\wwwroot\SitecoreIdentityServer\wwwroot\logs
    - .\build\commerce:C:\Workspace
  depends_on:
    - xconnect
    - mssql
    - solr
    - sitecore
  restart: on-failure
  ports:
    - "4022:4022"
  networks:
    app_net:
      ipv4_address: 172.16.3.2  

networks:
  app_net:
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.3.0/24
          gateway: 172.16.3.1
